"""Regression tests for `compare_filter_orders` parameter passthrough.

Background: when `substitute_real_components` gained `srf_margin` and
`max_value_drift_pct` parameters, the `compare_filter_orders` wrapper
didn't grow matching parameters. As a result, the comparison ran with
legacy semantics (no SRF gating) and could rank a winner whose
components a final design with SRF gating would actually reject —
breaking the "comparison reflects the design" promise.

The fix exposes these parameters on `compare_filter_orders` and threads
them through to the inner substitution call.
"""

from __future__ import annotations

import inspect

import pytest

from mcp_ltspice.compare import compare_filter_orders
from mcp_ltspice.vendor_models import substitute_real_components


def test_compare_signature_has_srf_margin_and_drift():
    """The wrapper must expose `srf_margin` and `max_value_drift_pct`."""
    sig = inspect.signature(compare_filter_orders)
    assert "srf_margin" in sig.parameters, (
        "compare_filter_orders must expose `srf_margin` so the comparison "
        "can use the same SRF gating as the final design."
    )
    assert "max_value_drift_pct" in sig.parameters, (
        "compare_filter_orders must expose `max_value_drift_pct` so the "
        "drift bound used inside the comparison matches the final design."
    )


def test_compare_param_set_supersets_substitute_real():
    """Structural test: every parameter on `substitute_real_components`
    that affects component selection must be reachable from
    `compare_filter_orders`. Catches future drift.

    Parameters that are derivable from existing compare inputs (e.g.
    ``max_spec_freq_hz`` is auto-derived from ``spec``) are excluded.
    """
    sub_sig = inspect.signature(substitute_real_components)
    cmp_sig = inspect.signature(compare_filter_orders)

    # `components` is generated by the comparison itself; `max_spec_freq_hz`
    # is auto-derived from `spec` (which compare already takes).
    excluded = {"components", "max_spec_freq_hz"}
    relevant = set(sub_sig.parameters) - excluded
    missing = relevant - set(cmp_sig.parameters)
    assert not missing, (
        f"compare_filter_orders is missing pass-through for parameters of "
        f"substitute_real_components: {missing}. When substitute_real_components "
        f"grows a new parameter, the comparison wrapper must follow (or the "
        f"new parameter must be added to the `excluded` set above with a comment "
        f"explaining why it's derivable from existing compare inputs)."
    )


@pytest.mark.parametrize("srf_margin, max_drift", [(0.0, None), (1.2, 30.0)])
def test_compare_runs_with_new_params(srf_margin: float, max_drift: float | None):
    """Smoke: compare_filter_orders accepts the new params and runs."""
    spec = {
        "passband": {
            "f_start": 100e6,
            "f_stop": 800e6,
            "il_max_db": 1.0,
            "rl_min_db": 14.0,
        },
        "stopband_targets": [
            {"freq": 1.6e9, "rejection_min_db": 30.0, "label": "2H"},
        ],
    }
    result = compare_filter_orders(
        orders=[5],  # single order, fastest
        cutoff_hz=1.0e9,
        spec=spec,
        zero_targets_hz=[1.6e9],
        ripple_db=0.1,
        stopband_atten_db=40.0,
        mc_n_runs=20,  # tiny — just smoke
        mc_tolerance_pct=2.0,
        srf_margin=srf_margin,
        max_value_drift_pct=max_drift,
    )
    assert result.winner_order == 5
    assert len(result.results) == 1
