"""Combine a design's artifacts into a single shareable PDF.

Walks a design directory, collects:
- Schematics (``*.schematic.png`` or per-stage ``schematic_stage_*.png``)
- Response plots (``response.png``, ``*_final.png``, ``*_lpf.png``)
- The textual report (``report.md``)

…and assembles them into a multi-page PDF via matplotlib's PdfPages.
The result is a self-contained artifact suitable for sharing,
attaching to an EE design review, or archiving alongside the BOM.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.image import imread


def _collect_artifacts(design_dir: Path) -> dict[str, list[Path]]:
    """Discover what PNGs and markdown files are present."""
    pngs = sorted(design_dir.glob("*.png"))
    schematic_pngs = [p for p in pngs if "schematic" in p.stem]
    response_pngs = [
        p
        for p in pngs
        if p not in schematic_pngs
        and (
            "response" in p.stem
            or "final" in p.stem
            or "_lpf" in p.stem
            or p.stem == design_dir.name
        )
    ]
    other_pngs = [p for p in pngs if p not in schematic_pngs and p not in response_pngs]
    md_files = sorted(design_dir.glob("*.md"))
    # Skip README.md; prefer report.md if present
    report_mds = [m for m in md_files if m.name.lower() != "readme.md"]
    if not report_mds:
        report_mds = md_files
    return {
        "schematics": schematic_pngs,
        "responses": response_pngs,
        "others": other_pngs,
        "reports": report_mds,
    }


def _add_image_page(pdf: PdfPages, image_path: Path, title: str) -> None:
    img = imread(image_path)
    fig = plt.figure(figsize=(11, 8.5), dpi=150)
    ax = fig.add_subplot(111)
    ax.imshow(img)
    ax.set_axis_off()
    ax.set_title(title, fontsize=14, pad=16)
    fig.tight_layout()
    pdf.savefig(fig)
    plt.close(fig)


def _add_text_page(pdf: PdfPages, lines: list[str], title: str) -> None:
    """Add a text page using monospace, with simple line wrapping."""
    fig = plt.figure(figsize=(8.5, 11), dpi=150)
    ax = fig.add_subplot(111)
    ax.set_axis_off()
    ax.set_title(title, fontsize=12, loc="left", pad=12)
    body = "\n".join(lines[:75])  # one page = up to ~75 lines of monospace
    ax.text(
        0.0,
        1.0,
        body,
        family="monospace",
        fontsize=8,
        verticalalignment="top",
        horizontalalignment="left",
        transform=ax.transAxes,
        wrap=True,
    )
    fig.tight_layout()
    pdf.savefig(fig)
    plt.close(fig)


def _split_markdown_into_pages(md_text: str, lines_per_page: int = 70) -> list[list[str]]:
    """Trivially split markdown into N-line chunks, breaking on blank
    lines when possible to avoid splitting inside a section."""
    raw = md_text.splitlines()
    pages: list[list[str]] = []
    current: list[str] = []
    for line in raw:
        current.append(line)
        if len(current) >= lines_per_page and (
            not line.strip() or len(current) >= lines_per_page + 10
        ):
            pages.append(current)
            current = []
    if current:
        pages.append(current)
    return pages


def _add_summary_page(pdf: PdfPages, design_dir: Path, artifacts: dict) -> None:
    """First page: design name + artifact inventory."""
    fig = plt.figure(figsize=(8.5, 11), dpi=150)
    ax = fig.add_subplot(111)
    ax.set_axis_off()

    title = design_dir.name.replace("_", " ").title()
    ax.text(
        0.5,
        0.92,
        title,
        fontsize=22,
        fontweight="bold",
        horizontalalignment="center",
        transform=ax.transAxes,
    )
    ax.text(
        0.5,
        0.86,
        "Design report",
        fontsize=12,
        color="#5b6f95",
        horizontalalignment="center",
        transform=ax.transAxes,
    )

    summary_lines = [
        "Design directory:  " + str(design_dir),
        "",
        f"Schematics:   {len(artifacts['schematics'])} ({', '.join(p.name for p in artifacts['schematics'][:5]) or 'none'})",
        f"Response plots: {len(artifacts['responses'])} ({', '.join(p.name for p in artifacts['responses'][:5]) or 'none'})",
        f"Other plots:  {len(artifacts['others'])}",
        f"Reports:      {len(artifacts['reports'])} ({', '.join(p.name for p in artifacts['reports'][:5]) or 'none'})",
        "",
        "Generated by mcp-ltspice / mcp_ltspice.report_pdf.build_design_report_pdf",
    ]
    ax.text(
        0.05,
        0.68,
        "\n".join(summary_lines),
        family="monospace",
        fontsize=9,
        verticalalignment="top",
        transform=ax.transAxes,
    )
    pdf.savefig(fig)
    plt.close(fig)


def build_design_report_pdf(
    design_dir: str | Path,
    output_pdf: str | Path,
    *,
    title: str | None = None,
) -> Path:
    """Build a single PDF combining all artifacts in ``design_dir``.

    Page layout:
        1. Title + artifact inventory
        2..N. One page per schematic PNG, then one per response PNG
        N+1..end. report.md (and any other .md) as text pages

    Returns the path to the written PDF.
    """
    d = Path(design_dir).expanduser().resolve()
    if not d.is_dir():
        raise NotADirectoryError(f"{d} is not a directory")
    out = Path(output_pdf).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    artifacts = _collect_artifacts(d)
    n_total_pages = (
        1 + len(artifacts["schematics"]) + len(artifacts["responses"]) + len(artifacts["others"])
    )
    if n_total_pages == 1 and not artifacts["reports"]:
        raise ValueError(f"{d} has no schematic / response PNGs or markdown report files")

    with PdfPages(out) as pdf:
        _add_summary_page(pdf, d, artifacts)

        for p in artifacts["schematics"]:
            _add_image_page(pdf, p, f"Schematic — {p.stem}")

        for p in artifacts["responses"]:
            _add_image_page(pdf, p, f"Response — {p.stem}")

        for p in artifacts["others"]:
            _add_image_page(pdf, p, p.stem)

        for md in artifacts["reports"]:
            md_text = md.read_text(encoding="utf-8", errors="replace")
            pages = _split_markdown_into_pages(md_text)
            for i, lines in enumerate(pages):
                title_str = f"{md.name}" + (
                    f"  (page {i + 1}/{len(pages)})" if len(pages) > 1 else ""
                )
                _add_text_page(pdf, lines, title_str)

    return out
